id: I64FAB04F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T22:41:50+00:00'
last_modified: '2022-06-15T18:47:21.294536+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22690
  title: བོད་དབྱིན་ཚིག་མཛོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D855:
      image_group_id: I1KG22732
      title: Volume 1 of bod dbyn mdzod mdzod/
      total_pages: 1278
      order: 1
      base_file: D855.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
