id: I64FAB04F
legacy_id: P000467
ocr_import_info:
  bdrc_scan_id: W1KG22690
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T22:34:06'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T13:19:01.719757+00:00'
last_modified: 2022-08-31 21:28:07.846556
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG22690
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG22690
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བོད་དབྱིན་ཚིག་མཛོད།
  author: h. a. jaschike
statistics:
  ocr_word_mean_confidence_index: 0.8442173882190622
  ocr_word_median_confidence_index: 0.9300000071525574
quality: null
bases:
  I1KG22732:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22732
      total_pages: 1278
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG22732.txt
    statistics:
      ocr_word_median_confidence_index: 0.9300000071525574
      ocr_word_mean_confidence_index: 0.8442173882190622
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
